
#include <exception>
using namespace std;


class exception_core: public exception {

    public:

    void Valor() const throw(){ }

};
